---
version: "3.0"

services:
  sqlite:
    image: "nouchka/sqlite3:latest"
    container_name: "api_gateway_sqlite"
    restart: always
    volumes:
      - sqlite_volume:/root/db

volumes:
  sqlite_volume:
