openapi: 3.0.0
info:
  title: "API Gateway"
  version: 1.0.0
paths:
  /{vendor+}:
    get:
      summary: Get a list of users
      x-tag: Vendor
    options:
      x-tag: Vendor
      summary: Get a list of users
    post:
      x-tag: Vendor
      summary: Get a list of users
    delete:
      x-tag: Vendor
      summary: Get a list of users
  /{customer+}:
    post:
      x-tag: Customers
      summary: Get a list of users
      x-target: "http://localhost:2022/customer"
    get:
      x-tag: Customers
      summary: Get a list of users
    delete:
      x-tag: Customers
      summary: Get a list of users
    options:
      x-tag: Customers
      summary: Get a list of users
    patch:
      x-tag: Customers
      summary: Get a list of users

tags:
  - name: Vendor
    description: User related actions
    x-target: "http://localhost:2021/vendor"
  - name: Customers
    description: Customer related actions
    x-target: "http://localhost:2022/customer"
